import Head from "next/head";
import Headers from "../components/Headers";
import Main1 from "../components/Main1";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ZH Squarenix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Headers />
      <main>
        <Main1 />
      </main>
    </div>
  );
}
