import Head from "next/head";
import dynamic from "next/dynamic";

const Headers = dynamic(() => import("../components/Headers"));
const Main1 = dynamic(() => import("../components/Main1"));

export default function Home() {
  return (
    <div>
      <Head>
        <title>ZH Squarenix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Headers />
      <main>
        <Main1 />
      </main>
    </div>
  );
}
